### ISSUE TITLE
xwidgets package doesn't come with Docker image

### ISSUE THREAD

**Issue by phesse001** [jupyter-xeus/xwidgets#190]
I am using the existing xeus-cling docker image to containerize a c++ project I have in a jupyter notebook. The only problem is, I was hoping on using the xwidgets package in this project, but the docker image does not come with the xwidgets package pre installed. It also doesn't come with a standard ubuntu or conda package manager, is there a clean way to get the xwidgets package in the docker image?

**Comment by SylvainCorlay** [comment]
Hey there, thank you for your interest in xeus-cling and xwidgets!

I am not aware of a specific docker image for xeus-cling, what docker image are you refering to?

A good means to generate docker image with such conda dependencies is to use repo2docker, which can consume a single manifest file specifying the requirements. repo2docker is at the foundation of mybinder.

**Comment by phesse001** [comment]
Here is the link to the image I pulled: [https://hub.docker.com/r/adiog/cling-jupyter/](url). I am not familiar with repo2docker, but I'll look in to that. I was hoping I would be able to just pull the image I linked and download xwidgets but once I found out the image wasn't using conda is seems like it may be more work then its worth. If there is and easy way to do it with the image I linked, let me know! Otherwise I will likely just learn how to use the repo2docker. Thanks for the response!

**Comment by phesse001** [comment]
You may have to copy paste the link I attached, doesn't seem to work if you just click it.

**Comment by phesse001** [comment]
@SylvainCorlay is the repo you used to make the xplot demo with binder just the QuantStack/xplot repo? And is all that it needed was the environments.yml and notebooks?

**Comment by phesse001** [comment]
Figured it out, Binder was super easy to use! So much easier then making a docker file, building the repo and running it interactively. Thanks for all the work and help Sylvain!
