### ISSUE TITLE
default build should not use march=native

### ISSUE THREAD

**Issue by joequant** [jupyter-xeus/xwidgets#193]
The default build should not use march=native as this generates executables that can break on other machines.

**Comment by SylvainCorlay** [comment]
Hey @joequant are you refering to the conda-forge package?

**Comment by joequant** [comment]
No.  I'm using the github source to build an RPM package for mageia linux.

**Comment by SylvainCorlay** [comment]
Cool!

We have a cmake option called `DISABLE_ARCH_NATIVE` set to `OFF` by default. Would that work for you?

**Comment by joequant** [comment]
Yes.  Exactly what I was thinking.

在 2020年8月7日 週五 17:21，Sylvain Corlay <notifications@github.com> 寫道：

**Comment by SylvainCorlay** [comment]
So I guess you can use that option in the recipe for the rpm package or am I missing something?

**Comment by joequant** [comment]
Yes.  But it might be a good idea to default it to not use native since it
leads to some hard to debug crashes.

在 2020年8月8日 週六 07:35，Sylvain Corlay <notifications@github.com> 寫道：

**Comment by JohanMabille** [comment]
We have removed the `-march=native` option form cmake.
