### ISSUE TITLE
[BUG] Typo in cmake config file prevents finding the library

### ISSUE THREAD

**Issue by rapgenic** [jupyter-xeus/xwidgets#234]
https://github.com/jupyter-xeus/xwidgets/blob/a9791a762af64c52f73cb028f1d4f6e2a9ef149f/xwidgetsConfig.cmake.in#L23

Should be 

```cmake
 find_dependency(xproperty @xproperty_REQUIRED_VERSION@) 
```

Right now it evaluates to `3.0.3` which is not an existing xproperty version string

**Comment by JohanMabille** [comment]
Good catch!
